### ISSUE TITLE
Playing prompts with FreeTTS crashes

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/cairo#48]
When trying to generate a prompt cairo crashes with

```
java.lang.IllegalArgumentException: Cannot add zero length or null content, to remove content use removeContent() instead!
	at org.mrcp4j.message.MrcpMessage.setContent(MrcpMessage.java:132) ~[?:?]
	at org.speechforge.cairo.client.SpeechClientImpl.play(SpeechClientImpl.java:432) ~[?:?]
	at org.speechforge.cairo.client.SpeechClientImpl.queuePrompt(SpeechClientImpl.java:821) ~[?:?]
	at org.jvoicexml.implementation.mrcpv2.Mrcpv2SynthesizedOutput.queueSpeakable(Mrcpv2SynthesizedOutput.java:164) ~[?:?]
	at org.jvoicexml.implementation.jvxml.JVoiceXmlSystemOutput.queueSpeakable(JVoiceXmlSystemOutput.java:87) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.queuePrompt(JVoiceXmlImplementationPlatform.java:1079) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.profile.vxml21.tagstrategy.TextStrategy.queueSpeakable(TextStrategy.java:128) ~[?:?]
	at org.jvoicexml.profile.vxml21.tagstrategy.TextStrategy.execute(TextStrategy.java:103) ~[?:?]
	at org.jvoicexml.profile.TagStrategyExecutor.executeTagStrategy(TagStrategyExecutor.java:235) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:207) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:84) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.FormInterpretationAlgorithm.visitBlockFormItem(FormInterpretationAlgorithm.java:1341) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.formitem.BlockFormItem.accept(BlockFormItem.java:108) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.FormInterpretationAlgorithm.collect(FormInterpretationAlgorithm.java:743) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.FormInterpretationAlgorithm.mainLoop(FormInterpretationAlgorithm.java:489) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.VoiceXmlInterpreter.process(VoiceXmlInterpreter.java:255) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:798) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:459) ~[org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
	at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:385) [org.jvoicexml-0.7.9-SNAPSHOT.jar:0.7.9-SNAPSHOT]
```

**Comment by schnelle** [comment]
Error was in JVoiceXML not sending the correct prompts. Closing here
