### ISSUE TITLE
NullPointerException on receiver1 console

### ISSUE THREAD

**Issue by FlorianRas** [JVoiceXML/cairo#51]
I started JvoiceXML browser and all the cairo console in order : rserver, receiver and transmitter.

But when I call the extension "0200" I wrote in sip-callmanager.xml, I got this error in receiver1 console:

```
 1095 [main                ] INFO  rver.resource.ReceiverResource (   326) [] looking up: rmi://DESKTOP-UP0A2TR/ResourceRegistry
  1990 [main                ] INFO  r.recog.sphinx.SphinxRecEngine (    94) [] Creating Engine # 1
  3655 [main                ] INFO  recorder.sphinx.SphinxRecorder (    63) [] Creating Recorder # 1
  3658 [main                ] INFO  rver.resource.ReceiverResource (   331) [] binding receiver resource...
  3680 [main                ] INFO  rver.resource.ReceiverResource (   334) [] Resource bound and waiting...
 52919 [RTPEventHandler     ] ERROR                     System.err (   748) [] Exception in thread "RTPEventHandler" java.lang.NullPointerException
 52919 [RTPEventHandler     ] ERROR                     System.err (   748) []  at org.speechforge.cairo.rtp.server.RTPStreamReplicator.streamInactive(RTPStreamReplicator.java:161)
 52920 [RTPEventHandler     ] ERROR                     System.err (   748) []  at org.speechforge.cairo.rtp.RTPConsumer.update(RTPConsumer.java:267)
 52920 [RTPEventHandler     ] ERROR                     System.err (   748) []  at com.sun.media.rtp.RTPEventHandler.processEvent(RTPEventHandler.java:62)
 52920 [RTPEventHandler     ] ERROR                     System.err (   748) []  at com.sun.media.rtp.RTPEventHandler.dispatchEvents(RTPEventHandler.java:96)
 52920 [RTPEventHandler     ] ERROR                     System.err (   748) []  at com.sun.media.rtp.RTPEventHandler.run(RTPEventHandler.java:115)
```

**Here's the cairo logfile:** 

[cairo.log](https://github.com/JVoiceXML/cairo/files/13216580/cairo.log)

And here's the JvoiceXML browser logfile: 

[jvoicexml.log](https://github.com/JVoiceXML/cairo/files/13216581/jvoicexml.log)

**Comment by schnelle** [comment]
A common interface for the 3 supported synthesizers are missing. So configuration for Mary trapped into a RuntimeException.
Additionally, OpenMary was not running, so the attempt to use the Mary client resulted into a NullPointerException. Added some more checks to avoid trapping into this exception and improved logging to ease finding of a misconfiguration
